var sutudent_number=prompt("Enter your number :")
var sutudent_number=parseInt(sutudent_number)

if(sutudent_number>100)
document.write("re-try this number is not available<h1>Please Enter 0-100</h1>")
else if(sutudent_number>=80 && sutudent_number<=100)
document.write("your grade is :A+","</br>","Pass")   
else if(sutudent_number>=70 && sutudent_number<=79)
document.write("your grade is :A","</br>","Pass")
else if(sutudent_number>=60 && sutudent_number<=69)
document.write("your grade is :A-","</br>","Pass")
else if(sutudent_number>=50 && sutudent_number<=59)
document.write("your grade is :B","</br>","Pass")
else if(sutudent_number>=40 && sutudent_number<=49)
document.write("your grade is :c","</br>","Pass")
else if(sutudent_number>=33 && sutudent_number<=39)
document.write("your grade is :D","</br>","Pass")
else
document.write("your grade is :F","</br>","Fail")